/* =============================================================================
 * rosters.js — Curated World Cup squad data (real players).
 *
 * This is the human-authored source of truth for card identities: who was on
 * each team, their position, and their individual honors. Exact match-by-match
 * stats are synthesized deterministically by generate-data.js from position +
 * star rating + explicit overrides, so the dataset is reproducible and the
 * rarity algorithm has real outcomes/honors to work from.
 *
 * Player token format (compact):
 *   [name, position, stars(1-5), "flags"]
 * Flags (space separated, all optional):
 *   sub          -> bench/reserve (not a starter in the deepest run)
 *   gb           -> Golden Ball
 *   gboot        -> Golden Boot
 *   at           -> All-Tournament team selection
 *   fg           -> scored in the final
 *   gN           -> goals = N           (e.g. g7)
 *   aN           -> assists = N         (e.g. a3)
 *   csN          -> clean sheets = N    (GK/DEF, e.g. cs5)
 *   ageN         -> age = N             (for the 35+ iconic rule)
 *   capt         -> captain (cosmetic, ignored by scoring)
 * ========================================================================== */
'use strict';

// stage drives team-level honors (winner/finalist/semifinalist/quarterfinalist)
// team = { country, stage, players:[ ...tokens ] }

const TOURNAMENTS = [
  /* =================================================================== 1970 */
  { year: 1970, host: 'Mexico', teams: [
    { country: 'Brazil', stage: 'Champion', players: [
      ['Félix', 'GK', 3, 'cs1'],
      ['Carlos Alberto', 'DEF', 5, 'capt g1 at'],
      ['Brito', 'DEF', 3, ''],
      ['Piazza', 'DEF', 4, ''],
      ['Everaldo', 'DEF', 3, ''],
      ['Clodoaldo', 'MID', 4, ''],
      ['Gérson', 'MID', 5, 'g1 a1 at'],
      ['Rivelino', 'MID', 5, 'g3 a3'],
      ['Jairzinho', 'FWD', 5, 'g7 at'],
      ['Tostão', 'FWD', 5, 'g2 a4'],
      ['Pelé', 'FWD', 5, 'g4 a6 gb at'],
      ['Paulo Cézar', 'MID', 3, 'sub'],
      ['Roberto Miranda', 'FWD', 2, 'sub'],
      ['Edu', 'FWD', 3, 'sub'],
      ['Marco Antônio', 'DEF', 2, 'sub'],
      ['Ado', 'GK', 1, 'sub'],
    ]},
    { country: 'Italy', stage: 'Finalist', players: [
      ['Enrico Albertosi', 'GK', 4, 'cs3'],
      ['Tarcisio Burgnich', 'DEF', 4, ''],
      ['Pierluigi Cera', 'DEF', 3, ''],
      ['Roberto Rosato', 'DEF', 3, ''],
      ['Giacinto Facchetti', 'DEF', 5, 'capt'],
      ['Mario Bertini', 'MID', 3, ''],
      ['Giancarlo De Sisti', 'MID', 4, ''],
      ['Sandro Mazzola', 'MID', 5, 'a2 at'],
      ['Angelo Domenghini', 'FWD', 3, 'g1'],
      ['Roberto Boninsegna', 'FWD', 4, 'g2'],
      ['Luigi Riva', 'FWD', 5, 'g3'],
      ['Gianni Rivera', 'MID', 5, 'sub g1'],
      ['Antonio Juliano', 'MID', 3, 'sub'],
      ['Giorgio Puia', 'DEF', 2, 'sub'],
    ]},
    { country: 'West Germany', stage: 'Semifinalist', players: [
      ['Sepp Maier', 'GK', 4, 'cs1'],
      ['Berti Vogts', 'DEF', 4, ''],
      ['Karl-Heinz Schnellinger', 'DEF', 4, ''],
      ['Franz Beckenbauer', 'DEF', 5, 'capt g1 a1 at'],
      ['Willi Schulz', 'DEF', 3, ''],
      ['Wolfgang Overath', 'MID', 4, 'g1'],
      ['Uwe Seeler', 'FWD', 5, 'g2 capt'],
      ['Reinhard Libuda', 'FWD', 3, 'g1'],
      ['Gerd Müller', 'FWD', 5, 'g10 gboot at'],
      ['Siegfried Held', 'FWD', 3, 'a2'],
      ['Hannes Löhr', 'MID', 3, ''],
      ['Jürgen Grabowski', 'FWD', 3, 'sub'],
      ['Klaus Fichtel', 'DEF', 2, 'sub'],
    ]},
    { country: 'Uruguay', stage: 'Semifinalist', players: [
      ['Ladislao Mazurkiewicz', 'GK', 4, 'cs2'],
      ['Atilio Ancheta', 'DEF', 3, ''],
      ['Roberto Matosas', 'DEF', 3, ''],
      ['Juan Mujica', 'DEF', 2, ''],
      ['Luis Ubiña', 'DEF', 3, 'capt'],
      ['Julio Montero Castillo', 'MID', 3, ''],
      ['Ildo Maneiro', 'MID', 3, ''],
      ['Víctor Espárrago', 'MID', 3, 'g1'],
      ['Luis Cubilla', 'FWD', 3, ''],
      ['Julio Morales', 'FWD', 3, ''],
      ['Pedro Rocha', 'FWD', 4, ''],
    ]},
    { country: 'England', stage: 'Quarterfinalist', players: [
      ['Gordon Banks', 'GK', 5, 'cs2'],
      ['Tommy Wright', 'DEF', 2, ''],
      ['Bobby Moore', 'DEF', 5, 'capt at'],
      ['Brian Labone', 'DEF', 3, ''],
      ['Terry Cooper', 'DEF', 3, ''],
      ['Alan Mullery', 'MID', 3, 'g1'],
      ['Bobby Charlton', 'MID', 5, ''],
      ['Alan Ball', 'MID', 4, ''],
      ['Martin Peters', 'MID', 4, 'g1'],
      ['Geoff Hurst', 'FWD', 4, 'g1'],
      ['Francis Lee', 'FWD', 3, ''],
      ['Peter Bonetti', 'GK', 2, 'sub'],
    ]},
    { country: 'Peru', stage: 'Quarterfinalist', players: [
      ['Luis Rubiños', 'GK', 2, ''],
      ['Eloy Campos', 'DEF', 2, ''],
      ['Héctor Chumpitaz', 'DEF', 4, 'capt g1'],
      ['Julio Meléndez', 'DEF', 3, ''],
      ['Teófilo Cubillas', 'MID', 5, 'g5 at'],
      ['Roberto Challe', 'MID', 3, 'g1'],
      ['Ramón Mifflin', 'MID', 3, ''],
      ['Hugo Sotil', 'FWD', 4, 'g1'],
      ['Alberto Gallardo', 'FWD', 3, 'g1'],
      ['Pedro León', 'FWD', 2, ''],
    ]},
  ]},

  /* =================================================================== 1986 */
  { year: 1986, host: 'Mexico', teams: [
    { country: 'Argentina', stage: 'Champion', players: [
      ['Nery Pumpido', 'GK', 3, 'cs2'],
      ['José Luis Cuciuffo', 'DEF', 3, ''],
      ['José Luis Brown', 'DEF', 4, 'g1 fg'],
      ['Oscar Ruggeri', 'DEF', 4, ''],
      ['Julio Olarticoechea', 'DEF', 3, ''],
      ['Ricardo Giusti', 'MID', 3, ''],
      ['Sergio Batista', 'MID', 3, ''],
      ['Jorge Burruchaga', 'MID', 4, 'g2 fg'],
      ['Héctor Enrique', 'MID', 3, ''],
      ['Diego Maradona', 'FWD', 5, 'capt g5 a5 gb at'],
      ['Jorge Valdano', 'FWD', 4, 'g4 fg'],
      ['Pedro Pasculli', 'FWD', 2, 'sub g1'],
      ['Néstor Clausen', 'DEF', 2, 'sub'],
      ['Marcelo Trobbiani', 'MID', 2, 'sub'],
    ]},
    { country: 'West Germany', stage: 'Finalist', players: [
      ['Harald Schumacher', 'GK', 4, 'cs2'],
      ['Thomas Berthold', 'DEF', 3, ''],
      ['Karlheinz Förster', 'DEF', 4, ''],
      ['Ditmar Jakobs', 'DEF', 3, ''],
      ['Hans-Peter Briegel', 'DEF', 4, ''],
      ['Andreas Brehme', 'DEF', 4, ''],
      ['Norbert Eder', 'MID', 3, ''],
      ['Lothar Matthäus', 'MID', 5, 'g1 a1 at'],
      ['Felix Magath', 'MID', 3, ''],
      ['Klaus Allofs', 'FWD', 3, 'g1'],
      ['Karl-Heinz Rummenigge', 'FWD', 5, 'capt g2 fg'],
      ['Rudi Völler', 'FWD', 4, 'g3 fg'],
      ['Dieter Hoeneß', 'FWD', 2, 'sub'],
    ]},
    { country: 'France', stage: 'Semifinalist', players: [
      ['Joël Bats', 'GK', 4, 'cs2'],
      ['Manuel Amoros', 'DEF', 4, ''],
      ['Patrick Battiston', 'DEF', 3, ''],
      ['Maxime Bossis', 'DEF', 4, ''],
      ['William Ayache', 'DEF', 3, ''],
      ['Jean Tigana', 'MID', 4, ''],
      ['Luis Fernández', 'MID', 4, 'g1'],
      ['Alain Giresse', 'MID', 4, 'g1'],
      ['Michel Platini', 'MID', 5, 'capt g2 a2 at'],
      ['Yannick Stopyra', 'FWD', 3, 'g1'],
      ['Jean-Pierre Papin', 'FWD', 4, 'g1'],
      ['Bruno Bellone', 'FWD', 2, 'sub g1'],
    ]},
    { country: 'Belgium', stage: 'Semifinalist', players: [
      ['Jean-Marie Pfaff', 'GK', 4, ''],
      ['Eric Gerets', 'DEF', 4, 'capt'],
      ['Michel De Wolf', 'DEF', 2, ''],
      ['Stéphane Demol', 'DEF', 3, 'g1'],
      ['Franky Vercauteren', 'MID', 4, ''],
      ['Enzo Scifo', 'MID', 4, ''],
      ['Jan Ceulemans', 'FWD', 4, 'g3'],
      ['Nico Claesen', 'FWD', 3, 'g2'],
      ['Daniel Veyt', 'FWD', 2, 'g1'],
      ['Leo Clijsters', 'DEF', 2, 'sub'],
    ]},
    { country: 'Brazil', stage: 'Quarterfinalist', players: [
      ['Carlos', 'GK', 3, ''],
      ['Josimar', 'DEF', 3, 'g2'],
      ['Júlio César', 'DEF', 3, ''],
      ['Edinho', 'DEF', 3, ''],
      ['Branco', 'DEF', 3, ''],
      ['Alemão', 'MID', 3, ''],
      ['Elzo', 'MID', 2, ''],
      ['Sócrates', 'MID', 5, 'capt g1'],
      ['Júnior', 'MID', 4, 'g1'],
      ['Careca', 'FWD', 5, 'g5 at'],
      ['Müller', 'FWD', 3, ''],
    ]},
    { country: 'England', stage: 'Quarterfinalist', players: [
      ['Peter Shilton', 'GK', 4, 'cs2'],
      ['Gary Stevens', 'DEF', 3, ''],
      ['Terry Butcher', 'DEF', 4, ''],
      ['Terry Fenwick', 'DEF', 3, ''],
      ['Kenny Sansom', 'DEF', 3, ''],
      ['Glenn Hoddle', 'MID', 4, 'a2'],
      ['Peter Reid', 'MID', 3, ''],
      ['Trevor Steven', 'MID', 3, ''],
      ['Steve Hodge', 'MID', 3, 'a1'],
      ['Gary Lineker', 'FWD', 5, 'g6 gboot'],
      ['Peter Beardsley', 'FWD', 4, 'g1'],
    ]},
  ]},

  /* =================================================================== 1998 */
  { year: 1998, host: 'France', teams: [
    { country: 'France', stage: 'Champion', players: [
      ['Fabien Barthez', 'GK', 4, 'cs4'],
      ['Lilian Thuram', 'DEF', 5, 'g2 at'],
      ['Laurent Blanc', 'DEF', 4, 'g1'],
      ['Marcel Desailly', 'DEF', 5, 'at'],
      ['Bixente Lizarazu', 'DEF', 4, ''],
      ['Didier Deschamps', 'MID', 4, 'capt'],
      ['Emmanuel Petit', 'MID', 4, 'g1 fg'],
      ['Christian Karembeu', 'MID', 3, ''],
      ['Zinedine Zidane', 'MID', 5, 'g2 fg at'],
      ['Youri Djorkaeff', 'MID', 4, ''],
      ['Stéphane Guivarc’h', 'FWD', 2, ''],
      ['Thierry Henry', 'FWD', 4, 'sub g3'],
      ['David Trezeguet', 'FWD', 3, 'sub'],
      ['Christophe Dugarry', 'FWD', 3, 'sub g1'],
      ['Patrick Vieira', 'MID', 4, 'sub'],
      ['Robert Pirès', 'MID', 3, 'sub'],
    ]},
    { country: 'Brazil', stage: 'Finalist', players: [
      ['Cláudio Taffarel', 'GK', 4, 'cs3'],
      ['Cafu', 'DEF', 5, ''],
      ['Aldair', 'DEF', 4, ''],
      ['Júnior Baiano', 'DEF', 3, ''],
      ['Roberto Carlos', 'DEF', 5, ''],
      ['Dunga', 'MID', 4, 'capt'],
      ['César Sampaio', 'MID', 3, 'g2'],
      ['Rivaldo', 'MID', 5, 'g3 a3 at'],
      ['Leonardo', 'MID', 3, 'g1'],
      ['Ronaldo', 'FWD', 5, 'g4 a3 gb at'],
      ['Bebeto', 'FWD', 4, 'g3'],
      ['Denílson', 'FWD', 3, 'sub'],
      ['Emerson', 'MID', 3, 'sub'],
      ['Zé Roberto', 'MID', 3, 'sub'],
    ]},
    { country: 'Croatia', stage: 'Semifinalist', players: [
      ['Dražen Ladić', 'GK', 3, 'cs2'],
      ['Igor Štimac', 'DEF', 3, ''],
      ['Slaven Bilić', 'DEF', 4, ''],
      ['Dario Šimić', 'DEF', 3, ''],
      ['Robert Jarni', 'DEF', 4, 'g1'],
      ['Aljoša Asanović', 'MID', 4, ''],
      ['Robert Prosinečki', 'MID', 5, 'g2 at'],
      ['Zvonimir Boban', 'MID', 4, 'capt'],
      ['Mario Stanić', 'MID', 3, ''],
      ['Davor Šuker', 'FWD', 5, 'g6 gboot at'],
      ['Goran Vlaović', 'FWD', 3, 'g1'],
    ]},
    { country: 'Netherlands', stage: 'Semifinalist', players: [
      ['Edwin van der Sar', 'GK', 4, 'cs2'],
      ['Michael Reiziger', 'DEF', 3, ''],
      ['Jaap Stam', 'DEF', 4, ''],
      ['Frank de Boer', 'DEF', 4, 'a1'],
      ['Arthur Numan', 'DEF', 3, ''],
      ['Edgar Davids', 'MID', 4, 'g1'],
      ['Phillip Cocu', 'MID', 4, ''],
      ['Ronald de Boer', 'MID', 3, 'g1'],
      ['Dennis Bergkamp', 'FWD', 5, 'g3 at'],
      ['Patrick Kluivert', 'FWD', 4, 'g4'],
      ['Marc Overmars', 'FWD', 4, 'g1'],
      ['Boudewijn Zenden', 'MID', 3, 'sub'],
    ]},
    { country: 'Italy', stage: 'Quarterfinalist', players: [
      ['Gianluca Pagliuca', 'GK', 4, 'cs3'],
      ['Giuseppe Bergomi', 'DEF', 4, ''],
      ['Fabio Cannavaro', 'DEF', 4, ''],
      ['Paolo Maldini', 'DEF', 5, 'capt'],
      ['Alessandro Costacurta', 'DEF', 4, ''],
      ['Dino Baggio', 'MID', 3, 'g1'],
      ['Demetrio Albertini', 'MID', 4, ''],
      ['Luigi Di Biagio', 'MID', 3, 'g1'],
      ['Gianluca Pessotto', 'DEF', 3, ''],
      ['Roberto Baggio', 'FWD', 5, 'g2 a2'],
      ['Christian Vieri', 'FWD', 5, 'g5'],
      ['Alessandro Del Piero', 'FWD', 4, 'sub'],
    ]},
    { country: 'Argentina', stage: 'Quarterfinalist', players: [
      ['Carlos Roa', 'GK', 3, 'cs2'],
      ['Roberto Ayala', 'DEF', 4, ''],
      ['José Chamot', 'DEF', 3, ''],
      ['Néstor Sensini', 'DEF', 3, ''],
      ['Javier Zanetti', 'DEF', 5, 'g1'],
      ['Diego Simeone', 'MID', 4, ''],
      ['Matías Almeyda', 'MID', 3, ''],
      ['Juan Sebastián Verón', 'MID', 4, ''],
      ['Ariel Ortega', 'MID', 4, 'g1'],
      ['Gabriel Batistuta', 'FWD', 5, 'g5'],
      ['Claudio López', 'FWD', 4, 'g1'],
    ]},
  ]},

  /* =================================================================== 2002 */
  { year: 2002, host: 'Korea/Japan', teams: [
    { country: 'Brazil', stage: 'Champion', players: [
      ['Marcos', 'GK', 4, 'cs2'],
      ['Cafu', 'DEF', 5, 'capt'],
      ['Lúcio', 'DEF', 4, 'at'],
      ['Roque Júnior', 'DEF', 3, ''],
      ['Roberto Carlos', 'DEF', 5, 'a3 at'],
      ['Edmílson', 'MID', 3, 'g1'],
      ['Gilberto Silva', 'MID', 4, ''],
      ['Kléberson', 'MID', 3, ''],
      ['Ronaldinho', 'MID', 5, 'g2 a2 at'],
      ['Rivaldo', 'FWD', 5, 'g5 at'],
      ['Ronaldo', 'FWD', 5, 'g8 gboot fg gb at'],
      ['Juninho Paulista', 'MID', 3, 'sub'],
      ['Denílson', 'FWD', 3, 'sub'],
      ['Dida', 'GK', 3, 'sub'],
    ]},
    { country: 'Germany', stage: 'Finalist', players: [
      ['Oliver Kahn', 'GK', 5, 'cs5 gb at'],
      ['Thomas Linke', 'DEF', 3, ''],
      ['Carsten Ramelow', 'DEF', 3, ''],
      ['Christoph Metzelder', 'DEF', 3, ''],
      ['Torsten Frings', 'DEF', 4, ''],
      ['Dietmar Hamann', 'MID', 4, ''],
      ['Bernd Schneider', 'MID', 4, ''],
      ['Michael Ballack', 'MID', 5, 'g3 at'],
      ['Jens Jeremies', 'MID', 3, ''],
      ['Miroslav Klose', 'FWD', 5, 'g5'],
      ['Oliver Neuville', 'FWD', 3, 'g1'],
      ['Oliver Bierhoff', 'FWD', 3, 'sub'],
    ]},
    { country: 'Turkey', stage: 'Semifinalist', players: [
      ['Rüştü Reçber', 'GK', 4, 'cs2 at'],
      ['Fatih Akyel', 'DEF', 3, ''],
      ['Alpay Özalan', 'DEF', 3, ''],
      ['Bülent Korkmaz', 'DEF', 3, ''],
      ['Ümit Davala', 'DEF', 3, 'g1'],
      ['Tugay Kerimoğlu', 'MID', 4, ''],
      ['Emre Belözoğlu', 'MID', 4, ''],
      ['Yıldıray Baştürk', 'MID', 3, ''],
      ['Hasan Şaş', 'FWD', 3, 'g2'],
      ['Hakan Şükür', 'FWD', 4, 'g1 fg'],
      ['İlhan Mansız', 'FWD', 3, 'sub g2'],
    ]},
    { country: 'South Korea', stage: 'Semifinalist', players: [
      ['Lee Woon-jae', 'GK', 4, 'cs2'],
      ['Choi Jin-cheul', 'DEF', 3, ''],
      ['Hong Myung-bo', 'DEF', 4, 'capt'],
      ['Kim Tae-young', 'DEF', 3, ''],
      ['Lee Young-pyo', 'DEF', 3, ''],
      ['Yoo Sang-chul', 'MID', 3, 'g1'],
      ['Kim Nam-il', 'MID', 3, ''],
      ['Park Ji-sung', 'MID', 4, 'g1'],
      ['Lee Eul-yong', 'MID', 3, ''],
      ['Hwang Sun-hong', 'FWD', 3, 'g1'],
      ['Seol Ki-hyeon', 'FWD', 3, 'g1'],
      ['Ahn Jung-hwan', 'FWD', 4, 'sub g2'],
    ]},
    { country: 'England', stage: 'Quarterfinalist', players: [
      ['David Seaman', 'GK', 4, 'cs2'],
      ['Danny Mills', 'DEF', 2, ''],
      ['Rio Ferdinand', 'DEF', 4, 'g1'],
      ['Sol Campbell', 'DEF', 4, ''],
      ['Ashley Cole', 'DEF', 4, ''],
      ['David Beckham', 'MID', 5, 'capt g1'],
      ['Paul Scholes', 'MID', 4, ''],
      ['Nicky Butt', 'MID', 3, ''],
      ['Trevor Sinclair', 'MID', 2, ''],
      ['Michael Owen', 'FWD', 5, 'g1'],
      ['Emile Heskey', 'FWD', 3, 'g1'],
    ]},
    { country: 'Spain', stage: 'Quarterfinalist', players: [
      ['Iker Casillas', 'GK', 4, 'cs2'],
      ['Carles Puyol', 'DEF', 4, ''],
      ['Fernando Hierro', 'DEF', 4, 'capt g1'],
      ['Miguel Ángel Nadal', 'DEF', 3, ''],
      ['Juanfran', 'DEF', 2, ''],
      ['Rubén Baraja', 'MID', 3, 'g1'],
      ['Iván Helguera', 'MID', 3, 'g1'],
      ['Juan Carlos Valerón', 'MID', 4, ''],
      ['Gaizka Mendieta', 'MID', 4, 'sub'],
      ['Raúl', 'FWD', 5, 'g3'],
      ['Fernando Morientes', 'FWD', 4, 'g1'],
    ]},
  ]},

  /* =================================================================== 2014 */
  { year: 2014, host: 'Brazil', teams: [
    { country: 'Germany', stage: 'Champion', players: [
      ['Manuel Neuer', 'GK', 5, 'cs4 at'],
      ['Philipp Lahm', 'DEF', 5, 'capt'],
      ['Jérôme Boateng', 'DEF', 4, ''],
      ['Mats Hummels', 'DEF', 4, 'g1 at'],
      ['Benedikt Höwedes', 'DEF', 3, ''],
      ['Sami Khedira', 'MID', 4, ''],
      ['Bastian Schweinsteiger', 'MID', 5, ''],
      ['Toni Kroos', 'MID', 5, 'g2 a4 at'],
      ['Mesut Özil', 'MID', 4, 'g1'],
      ['Thomas Müller', 'FWD', 5, 'g5 a3 at'],
      ['Miroslav Klose', 'FWD', 4, 'g2'],
      ['Mario Götze', 'FWD', 4, 'sub g1 fg'],
      ['André Schürrle', 'FWD', 4, 'sub g3'],
      ['Per Mertesacker', 'DEF', 3, 'sub'],
    ]},
    { country: 'Argentina', stage: 'Finalist', players: [
      ['Sergio Romero', 'GK', 4, 'cs4'],
      ['Pablo Zabaleta', 'DEF', 4, ''],
      ['Ezequiel Garay', 'DEF', 4, ''],
      ['Martín Demichelis', 'DEF', 3, ''],
      ['Marcos Rojo', 'DEF', 3, 'g1'],
      ['Javier Mascherano', 'MID', 5, 'at'],
      ['Lucas Biglia', 'MID', 3, ''],
      ['Ángel Di María', 'MID', 5, 'g1'],
      ['Ezequiel Lavezzi', 'FWD', 3, ''],
      ['Gonzalo Higuaín', 'FWD', 4, 'g1'],
      ['Lionel Messi', 'FWD', 5, 'capt g4 a1 gb at'],
      ['Sergio Agüero', 'FWD', 4, 'sub'],
      ['Rodrigo Palacio', 'FWD', 3, 'sub'],
    ]},
    { country: 'Netherlands', stage: 'Semifinalist', players: [
      ['Jasper Cillessen', 'GK', 3, 'cs2'],
      ['Ron Vlaar', 'DEF', 4, 'at'],
      ['Stefan de Vrij', 'DEF', 3, 'g1'],
      ['Bruno Martins Indi', 'DEF', 3, ''],
      ['Daley Blind', 'DEF', 4, 'a2'],
      ['Nigel de Jong', 'MID', 4, ''],
      ['Georginio Wijnaldum', 'MID', 3, ''],
      ['Wesley Sneijder', 'MID', 4, 'g1'],
      ['Arjen Robben', 'FWD', 5, 'g3 a1 at'],
      ['Robin van Persie', 'FWD', 5, 'g4'],
      ['Memphis Depay', 'FWD', 3, 'sub g2'],
      ['Tim Krul', 'GK', 3, 'sub'],
    ]},
    { country: 'Brazil', stage: 'Semifinalist', players: [
      ['Júlio César', 'GK', 4, 'cs1'],
      ['Dani Alves', 'DEF', 4, ''],
      ['Thiago Silva', 'DEF', 5, 'capt'],
      ['David Luiz', 'DEF', 4, 'g2'],
      ['Marcelo', 'DEF', 4, 'a1'],
      ['Luiz Gustavo', 'MID', 3, ''],
      ['Fernandinho', 'MID', 3, ''],
      ['Oscar', 'MID', 4, 'g1'],
      ['Hulk', 'FWD', 3, ''],
      ['Fred', 'FWD', 3, 'g1'],
      ['Neymar', 'FWD', 5, 'g4 a1 at'],
    ]},
    { country: 'Colombia', stage: 'Quarterfinalist', players: [
      ['David Ospina', 'GK', 4, 'cs2'],
      ['Camilo Zúñiga', 'DEF', 3, 'a1'],
      ['Mario Yepes', 'DEF', 3, 'capt'],
      ['Cristián Zapata', 'DEF', 3, ''],
      ['Pablo Armero', 'DEF', 3, 'g1'],
      ['Juan Cuadrado', 'MID', 4, 'g1 a4'],
      ['Carlos Sánchez', 'MID', 3, ''],
      ['Abel Aguilar', 'MID', 3, ''],
      ['James Rodríguez', 'MID', 5, 'g6 a2 gboot at'],
      ['Teófilo Gutiérrez', 'FWD', 3, 'g1'],
      ['Jackson Martínez', 'FWD', 3, 'g2'],
    ]},
    { country: 'France', stage: 'Quarterfinalist', players: [
      ['Hugo Lloris', 'GK', 4, 'capt cs2'],
      ['Mathieu Debuchy', 'DEF', 3, ''],
      ['Raphaël Varane', 'DEF', 4, ''],
      ['Mamadou Sakho', 'DEF', 3, ''],
      ['Patrice Evra', 'DEF', 3, ''],
      ['Yohan Cabaye', 'MID', 3, 'g1'],
      ['Paul Pogba', 'MID', 4, 'g1'],
      ['Blaise Matuidi', 'MID', 4, ''],
      ['Mathieu Valbuena', 'MID', 3, 'a2'],
      ['Karim Benzema', 'FWD', 5, 'g3 a2'],
      ['Olivier Giroud', 'FWD', 3, ''],
      ['Antoine Griezmann', 'FWD', 4, 'sub'],
    ]},
  ]},

  /* =================================================================== 2022 */
  { year: 2022, host: 'Qatar', teams: [
    { country: 'Argentina', stage: 'Champion', players: [
      ['Emiliano Martínez', 'GK', 5, 'cs2 at'],
      ['Nahuel Molina', 'DEF', 3, 'g1'],
      ['Cristian Romero', 'DEF', 4, ''],
      ['Nicolás Otamendi', 'DEF', 4, ''],
      ['Nicolás Tagliafico', 'DEF', 3, ''],
      ['Rodrigo De Paul', 'MID', 4, ''],
      ['Enzo Fernández', 'MID', 4, 'g1'],
      ['Alexis Mac Allister', 'MID', 4, 'g1 a1'],
      ['Ángel Di María', 'MID', 5, 'g1 fg'],
      ['Lionel Messi', 'FWD', 5, 'capt g7 a3 gb at age35 fg'],
      ['Julián Álvarez', 'FWD', 4, 'g4'],
      ['Gonzalo Montiel', 'DEF', 3, 'sub'],
      ['Marcos Acuña', 'DEF', 3, 'sub'],
      ['Leandro Paredes', 'MID', 3, 'sub'],
      ['Lautaro Martínez', 'FWD', 3, 'sub'],
    ]},
    { country: 'France', stage: 'Finalist', players: [
      ['Hugo Lloris', 'GK', 4, 'capt cs2'],
      ['Jules Koundé', 'DEF', 4, ''],
      ['Raphaël Varane', 'DEF', 4, ''],
      ['Dayot Upamecano', 'DEF', 3, ''],
      ['Theo Hernández', 'DEF', 4, 'g1'],
      ['Aurélien Tchouaméni', 'MID', 4, 'g1'],
      ['Adrien Rabiot', 'MID', 4, 'g1'],
      ['Antoine Griezmann', 'MID', 5, 'a2 at'],
      ['Ousmane Dembélé', 'FWD', 4, ''],
      ['Kylian Mbappé', 'FWD', 5, 'g8 a2 gboot fg at'],
      ['Olivier Giroud', 'FWD', 4, 'g4'],
      ['Randal Kolo Muani', 'FWD', 3, 'sub g1'],
      ['Marcus Thuram', 'FWD', 3, 'sub'],
      ['Eduardo Camavinga', 'MID', 3, 'sub'],
    ]},
    { country: 'Croatia', stage: 'Semifinalist', players: [
      ['Dominik Livaković', 'GK', 4, 'cs2 at'],
      ['Josip Juranović', 'DEF', 3, ''],
      ['Dejan Lovren', 'DEF', 3, ''],
      ['Joško Gvardiol', 'DEF', 4, 'at'],
      ['Borna Sosa', 'DEF', 3, ''],
      ['Marcelo Brozović', 'MID', 4, ''],
      ['Luka Modrić', 'MID', 5, 'capt at'],
      ['Mateo Kovačić', 'MID', 4, ''],
      ['Mario Pašalić', 'MID', 3, ''],
      ['Andrej Kramarić', 'FWD', 3, 'g2'],
      ['Ivan Perišić', 'FWD', 4, 'g1 a1'],
      ['Mislav Oršić', 'FWD', 3, 'sub g1'],
    ]},
    { country: 'Morocco', stage: 'Semifinalist', players: [
      ['Yassine Bounou', 'GK', 4, 'cs3'],
      ['Achraf Hakimi', 'DEF', 4, ''],
      ['Romain Saïss', 'DEF', 3, 'capt'],
      ['Nayef Aguerd', 'DEF', 3, ''],
      ['Noussair Mazraoui', 'DEF', 3, ''],
      ['Sofyan Amrabat', 'MID', 4, 'at'],
      ['Azzedine Ounahi', 'MID', 3, ''],
      ['Selim Amallah', 'MID', 3, ''],
      ['Hakim Ziyech', 'FWD', 4, ''],
      ['Youssef En-Nesyri', 'FWD', 3, 'g2'],
      ['Sofiane Boufal', 'FWD', 3, ''],
    ]},
    { country: 'Brazil', stage: 'Quarterfinalist', players: [
      ['Alisson', 'GK', 5, 'cs3'],
      ['Danilo', 'DEF', 3, ''],
      ['Marquinhos', 'DEF', 4, ''],
      ['Thiago Silva', 'DEF', 4, 'capt'],
      ['Éder Militão', 'DEF', 3, ''],
      ['Casemiro', 'MID', 4, 'g1'],
      ['Lucas Paquetá', 'MID', 3, ''],
      ['Neymar', 'FWD', 5, 'g2 a1'],
      ['Raphinha', 'FWD', 3, ''],
      ['Vinícius Júnior', 'FWD', 4, 'g1'],
      ['Richarlison', 'FWD', 4, 'g3'],
    ]},
    { country: 'Netherlands', stage: 'Quarterfinalist', players: [
      ['Andries Noppert', 'GK', 3, 'cs2'],
      ['Denzel Dumfries', 'DEF', 4, 'g1 a2'],
      ['Jurriën Timber', 'DEF', 3, ''],
      ['Virgil van Dijk', 'DEF', 5, 'capt'],
      ['Nathan Aké', 'DEF', 3, ''],
      ['Daley Blind', 'DEF', 3, 'g1'],
      ['Frenkie de Jong', 'MID', 5, ''],
      ['Marten de Roon', 'MID', 3, ''],
      ['Steven Berghuis', 'MID', 3, ''],
      ['Cody Gakpo', 'FWD', 4, 'g3'],
      ['Memphis Depay', 'FWD', 4, 'g1'],
    ]},
    { country: 'England', stage: 'Quarterfinalist', players: [
      ['Jordan Pickford', 'GK', 4, 'cs3'],
      ['Kyle Walker', 'DEF', 4, ''],
      ['John Stones', 'DEF', 4, ''],
      ['Harry Maguire', 'DEF', 3, ''],
      ['Luke Shaw', 'DEF', 3, 'a2'],
      ['Declan Rice', 'MID', 4, ''],
      ['Jude Bellingham', 'MID', 4, 'a1'],
      ['Jordan Henderson', 'MID', 3, 'g1'],
      ['Bukayo Saka', 'FWD', 4, 'g2'],
      ['Harry Kane', 'FWD', 5, 'capt g2 a3'],
      ['Phil Foden', 'FWD', 4, 'sub'],
    ]},
    { country: 'Portugal', stage: 'Quarterfinalist', players: [
      ['Diogo Costa', 'GK', 4, 'cs2'],
      ['Diogo Dalot', 'DEF', 3, ''],
      ['Pepe', 'DEF', 3, 'g1'],
      ['Rúben Dias', 'DEF', 4, ''],
      ['Raphaël Guerreiro', 'DEF', 3, ''],
      ['William Carvalho', 'MID', 3, ''],
      ['Rúben Neves', 'MID', 3, ''],
      ['Bruno Fernandes', 'MID', 4, 'g2 a3'],
      ['Gonçalo Ramos', 'FWD', 3, 'g3 a1'],
      ['João Félix', 'FWD', 3, 'g1'],
      ['Cristiano Ronaldo', 'FWD', 5, 'capt g1'],
      ['Rafael Leão', 'FWD', 3, 'sub g1'],
    ]},
  ]},
];

module.exports = { TOURNAMENTS };
